apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-redis-deployment
  labels:
    app: webserver
spec:
  replicas: 5
  selector:
    matchLabels:
     app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - webserver
                topologyKey: "kubernetes.io/hostname"
      containers:
       - name: nginx
         image: nginx:1.9.1
       - name: redis
         imagePullPolicy: IfNotPresent
         image: redis
