apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-redis-deployment
  labels:
    app: webserver
spec:
  replicas: 5
  selector:
    matchLabels:
     app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
       - name: nginx
         image: nginx:1.9.1
       - name: redis
         imagePullPolicy: IfNotPresent
         image: redis

---

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: pdb-demo
spec:
  maxUnavailable: 2
  selector:
    matchLabels:
      app: webserver
