apiVersion: v1
kind: ServiceAccount
metadata:
  name: arcus-operator

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: arcus-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - "get"
  - "create"

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: arcus-operator
subjects:
- kind: ServiceAccount
  name: arcus-operator
roleRef:
  kind: Role
  name: arcus-operator
  apiGroup: rbac.authorization.k8s.io
