apiVersion: v1
kind: ConfigMap
metadata:
  name: arcus-zk-cm-node
data:
  zk-node.sh: |
    #!/bin/bash

    set -e

    # no need to edit
    ZK_CLI="$ZOOKEEPER_PATH/bin/zkCli.sh"

    # edit your zk address
    ZK_ADDR="-server arcus-zk-1.arcus-zk-svc.default.svc.cluster.local:2181"

    # edit your zk node
    $ZK_CLI $ZK_ADDR create /arcus 0
    $ZK_CLI $ZK_ADDR create /arcus/client_list 0
    $ZK_CLI $ZK_ADDR create /arcus/client_list/test 0
    $ZK_CLI $ZK_ADDR create /arcus/cache_list 0
    $ZK_CLI $ZK_ADDR create /arcus/cache_list/test 0
    $ZK_CLI $ZK_ADDR create /arcus/cache_server_mapping 0
    $ZK_CLI $ZK_ADDR create /arcus/cache_server_mapping/arcus-memcached-0.arcus-memcached-svc.default.svc.cluster.local:11200 0
    $ZK_CLI $ZK_ADDR create /arcus/cache_server_mapping/arcus-memcached-0.arcus-memcached-svc.default.svc.cluster.local:11200/test
---
apiVersion: batch/v1
kind: Job
metadata:
  name: arcus-zk-job-node
spec:
  template:
    spec:
      volumes:
        - name: arcus-zk-vol-node
          configMap:
            name: arcus-zk-cm-node
            defaultMode: 0775
      containers:
      - name: arcus-zk-job-node
        image: jam2in/arcus:latest
        command: ["/scripts/zk-node.sh"]
        volumeMounts:
          - mountPath: /scripts
            name: arcus-zk-vol-node
      restartPolicy: Never
  backoffLimit: 4
