apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: arcus.jam2in.com
spec:
  group: jam2in.com
  names:
    kind: Arcus
    listKind: ArcusList
    plural: arcus
    singular: arcus
  scope: Namespaced
  version: v1
  subresources:
    status: {}
